import SwiftUI
import PDFKit

// MARK: - PDF network report
// Renders a scan session into a multi-section PDF security report using
// ImageRenderer, suitable for sharing or archiving.

enum ReportPDF {

    @MainActor
    static func generate(for session: ScanSession) -> URL? {
        let pageWidth: CGFloat = 612   // US Letter width @72dpi
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("NetSweep-Report-\(Int(session.date.timeIntervalSince1970)).pdf")

        let content = ReportDocument(session: session).frame(width: pageWidth)
        let renderer = ImageRenderer(content: content)
        renderer.proposedSize = .init(width: pageWidth, height: nil)

        var result: URL?
        renderer.render { size, render in
            var box = CGRect(x: 0, y: 0, width: size.width, height: size.height)
            guard let consumer = CGDataConsumer(url: url as CFURL),
                  let ctx = CGContext(consumer: consumer, mediaBox: &box, nil) else { return }
            ctx.beginPDFPage(nil)
            render(ctx)
            ctx.endPDFPage()
            ctx.closePDF()
            result = url
        }
        return result
    }
}

// MARK: - The printable document (light theme for paper)

private struct ReportDocument: View {
    let session: ScanSession

    private var findings: [Finding] { session.findings.sorted { $0.severity > $1.severity } }
    private var devices: [DeviceRecord] {
        session.devices.sorted { (NetInfo.ipToUInt32($0.ip) ?? 0) < (NetInfo.ipToUInt32($1.ip) ?? 0) }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            // Header
            HStack {
                Image(systemName: "scope").font(.title)
                VStack(alignment: .leading, spacing: 2) {
                    Text("NETSWEEP").font(.system(.title2, design: .monospaced).weight(.heavy))
                    Text("Network Security Report").font(.system(.subheadline, design: .monospaced))
                        .foregroundStyle(.secondary)
                }
            }
            Divider()

            // Summary
            Group {
                row("Date", session.date.formatted(date: .long, time: .shortened))
                row("Network", session.subnet)
                row("Health Score", "\(session.healthScore) / 100 — \(SecurityAnalysis.grade(session.healthScore).0)")
                row("Devices", "\(session.deviceCount)")
                row("New devices", "\(session.newDeviceCount)")
            }
            Divider()

            // Findings
            Text("FINDINGS (\(findings.count))").font(.system(.headline, design: .monospaced))
            ForEach(findings) { f in
                VStack(alignment: .leading, spacing: 2) {
                    Text("[\(f.severity.label)] \(f.title)")
                        .font(.system(.subheadline, design: .monospaced).weight(.semibold))
                    Text(f.detail).font(.system(.caption, design: .monospaced)).foregroundStyle(.secondary)
                }
                .padding(.bottom, 4)
            }
            Divider()

            // Devices
            Text("DEVICES (\(devices.count))").font(.system(.headline, design: .monospaced))
            ForEach(devices) { d in
                HStack(alignment: .top) {
                    Text(d.ip).font(.system(.caption, design: .monospaced).weight(.semibold))
                        .frame(width: 110, alignment: .leading)
                    VStack(alignment: .leading, spacing: 1) {
                        Text(d.hostname ?? d.vendorGuess ?? "—").font(.system(.caption, design: .monospaced))
                        if !d.openPorts.isEmpty {
                            Text("ports: " + d.openPorts.map(String.init).joined(separator: ", "))
                                .font(.system(size: 9, design: .monospaced)).foregroundStyle(.secondary)
                        }
                    }
                    Spacer()
                    if d.isNew { Text("NEW").font(.system(size: 9, design: .monospaced).weight(.bold)) }
                }
                .padding(.bottom, 2)
            }

            Spacer(minLength: 12)
            Text("Generated by NetSweep. Audit your own networks only.")
                .font(.system(size: 9, design: .monospaced)).foregroundStyle(.secondary)
        }
        .padding(32)
        .foregroundStyle(.black)
        .background(.white)
    }

    private func row(_ k: String, _ v: String) -> some View {
        HStack {
            Text(k).font(.system(.caption, design: .monospaced)).foregroundStyle(.secondary)
            Spacer()
            Text(v).font(.system(.caption, design: .monospaced).weight(.medium))
        }
    }
}
